[package]
name = "pallet-evm-precompile-czk-precompiles"
version = "0.1.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
czk-precompiles = { git = "ssh://git@github.com.chainzk/Chainzk-org/czk-precompiles.git", branch = "deps" } 
fp-evm = { workspace = true }
